[package]
name = "game_client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.13"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }